- name: Manage slaves
  hosts: slave-std1
  connection: ssh
  sudo: True
  sudo_user: root
  roles:
    - { role: ansible-docker, tags: ['os-tools'] }
    - { role: ansible-mesos, mesos_version: "0.22.1", tags: ['mesos', 'platforms'], mesos_install_mode: "slave", zookeeper_hostnames: "{{ groups.zookeepers | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}" }
  tasks:
    - name: Check if already configured
      shell: test -e /usr/local/etc/mesos-flag; echo $?
      ignore_errors: yes
      register: test
    - name: Add user to docker group
      user:
        name: ubuntu
        append: yes
        groups: docker
      when: test.stdout != "0"
    - name: Initialize mesos-slave
      raw: mesos init-wrapper slave &
      when: test.stdout != "0"
    - name: Create mesos-flag
      raw: touch /usr/local/etc/mesos-flag
      when: test.stdout != "0"
